### ISSUE TITLE
Not compatible with live-only ha-policy

### ISSUE THREAD

**Issue by elmuerte** [markt-de/puppet-activemq#4]
https://github.com/markt-de/puppet-activemq/blob/13b127d8acfa5ce9acb47ba90c1a332f1ad6733f/templates/broker.xml.epp#L159-L188

If you want to set up a cluster without having persistent replication, i.e. live-only. This module will produce an invalid configuration file.

If you want the default cluster configuration of Artemis you would omit the whole `<ha-policy>` element. But this is not possible. 
If you set the `$ha-policy` to `live-only` it will start producing invalid configurations like:

```xml
<ha-policy>
	<live-only>
		<scale-down>
			<master>
				<group-name>devgroup</group-name>
				<cluster-name>development</cluster-name>
			</master>
		</scale-down>
	</live-only>
</ha-policy>
```

```
ERROR [org.apache.activemq.artemis.core.client] AMQ214019: Invalid configuration
org.xml.sax.SAXParseException: cvc-complex-type.2.4.a: Invalid content was found starting with element '{"urn:activemq:core":master}'. One of '{"urn:activemq:core":enabled, "urn:activemq:core":group-name, "urn:activemq:core":discovery-group-ref, "urn:activemq:core":connectors}' is expected.
```

The correct config would be either no `ha-policy` element. Or

```xml
<ha-policy>
	<live-only />
</ha-policy>
```

Further more, using [live-only with scale down](https://activemq.apache.org/components/artemis/documentation/latest/ha.html#scaling-down) is also not possible. Due to the way the config is created.

See also the [schema for live-only](https://github.com/apache/activemq-artemis/blob/fef7c147eb1229471b726c9c6898057036c3bdb1/artemis-server/src/main/resources/schema/artemis-configuration.xsd#L2970)

**Comment by fraenki** [comment]
resolved in #6
